blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    #widoki posta
    #path('', views.post_list, name='post_list'),
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/share/',
        views.post_share, name='post_share'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                    self).get_queryset()\
                         .filter(status='published')

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft') ,
        ('published' , 'Published') ,
    )
    objects = models.Manager()  # manager domyślny
    published = PublishedManager()  # manager niestandardowy

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[
                           self.publish.year,
                           self.publish.strftime('%m'),
                           self.publish.strftime('%d'),
                           self.slug])
    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title
# Create your models here.

blog/forms.py
from django import forms
class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from .forms import EmailPostForm
from django.core.mail import send_mail
# Create your views here.
def post_share(request, post_id):
    #pobranie posta na podstawie jego indentyfikatora
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        #formularz został wysłany
        form = EmailPostForm(request.POST)
        if form.is_valid():
            #weryfikacja pól formularza zakończyła się powodzeniem...
            cd = form.cleaned_data
            #można wysłać wiadomość
            post_url = request.build_absolute_uri(
                                        post.get_absolute_url())
            subject = '{} ({}) zachęca do przeczytania "{}"'.format(cd['name'], cd['email'], post.title)
            message = 'Przeczytaj post "{}" na stronie {}\n\n Komentarz dodany przez {}: {}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form':form,
                                                    'sent': sent})
def post_list(request):
    posts = Post.published.all()
    object_list = Post.published.all()
    paginator = Paginator(object_list, 3) #trzy posty na każdej stronie
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        #jeżeli zmienna page nie jest liczbą całkowitą wtedy pobierana jest pierwsza strona wyników
        posts = paginator.page(1)
    except EmptyPage:
        #jeżeli zmienna page ma wartość większą niż numer ostatniej strony wyników, wtedy pobierana jest ostatania strona wyników
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts})
def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    return render(request,
                  'blog/post/detail.html',
                  {'post': post})
class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static "css/blog.css" %}" rel="stylesheet" type="text/css">
</head>
<body>
<div id="content">
    {% block content %}
    {% endblock %}
</div>
<div id="sidebar">
    <h2>Mój blog</h2>
    <p>To jest mój blog.</p>
</div>
</body>
</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}
  <h1>{{ podt.title }}</h1>
  <p class="date">
    Opublikowany {{ post.publish }} przez {{ post.author }}
    </p>
    {{ post.body|linebreaks }}
  <p>
    <a href="{% url "blog:post_share" post.id %}">
    Udostępnij post
    </a>
  </p>
{% endblock content %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}Mój blog{% endblock %}
{% block content %}
  <h1>Mój blog</h1>
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
      {{ post.title }}
      </a>
    </h2>
    <p class="date">
      Opublikowany {{ post.publish }} przez {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
  {% endfor %}
  {% include "pagination.html" with page=page_obj %}
{% endblock content %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Udostępnij post{% endblock %}
{% block content %}
  {% if sent %}
    <h1>Wiadomość e-mail została wysłana</h1>
    <p>
      Wysłanie posta "{{ post.title }}" do {{ cd.to }} zakończyło się sukcesem.
    </p>
    {% else %}
      <h1>Udostępnij "{{ post.title }}" przez e-mail</h1>
      <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Wyślij wiadomość e-mail">
      </form>
  {% endif %}
{% endblock %}

blog/templates/pagination.html
<div class="pagination">
  <span class="step-links">
    {% if page.has_previous %}
      <a href="?page={{ page.previous_page_number }}">poprzednia</a>
    {% endif %}
    <span class="current">
    Strona {{ page.number }} z {{ page.paginator.num_pages }}.
    </span>
    {% if page.has_next %}
      <a href="?page={{ page.next_page_number }}">Następna</a>
    {% endif %}
  </span>
</div>